"""initial schema

Revision ID: 5392fbd9b8d2
Revises: 
Create Date: 2025-07-20 22:53:42.540613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5392fbd9b8d2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('coordinates', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('counters',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('area_id', sa.UUID(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('in_count', sa.Integer(), nullable=True),
    sa.Column('out_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detections',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tracking_id', sa.String(), nullable=False),
    sa.Column('area_id', sa.UUID(), nullable=True),
    sa.Column('frame_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=False),
    sa.Column('entered', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detections')
    op.drop_table('counters')
    op.drop_table('areas')
    # ### end Alembic commands ###
