"""fix counters schema, add updated_at

Revision ID: d57214663ac6
Revises: 5392fbd9b8d2
Create Date: 2025-07-22 21:19:05.520609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd57214663ac6'
down_revision: Union[str, Sequence[str], None] = '5392fbd9b8d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('counters', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_unique_constraint(None, 'counters', ['area_id'])
    op.drop_column('counters', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('counters', sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'counters', type_='unique')
    op.drop_column('counters', 'updated_at')
    # ### end Alembic commands ###
