"""add polygon field to areas table

Revision ID: e699604e4e78
Revises: d57214663ac6
Create Date: 2025-07-22 23:05:49.937524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e699604e4e78'
down_revision: Union[str, Sequence[str], None] = 'd57214663ac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('areas', sa.Column('polygon', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('areas', 'polygon')
    # ### end Alembic commands ###
